// Generated from playerglobal.swc by tools/as3-to-ts/gen-constants.ts. Do not edit.
export const FLASH_CONSTANTS: Record<string, Record<string, unknown>> = {
    "flash.automation.KeyboardAutomationAction": { KEY_DOWN: "keyDown", KEY_UP: "keyUp" },
    "flash.automation.MouseAutomationAction": { MOUSE_DOWN: "mouseDown", MOUSE_MOVE: "mouseMove", MOUSE_UP: "mouseUp", MOUSE_WHEEL: "mouseWheel", MIDDLE_MOUSE_DOWN: "middleMouseDown", MIDDLE_MOUSE_UP: "middleMouseUp", RIGHT_MOUSE_DOWN: "rightMouseDown", RIGHT_MOUSE_UP: "rightMouseUp" },
    "flash.automation.StageCapture": { CURRENT: "current", NEXT: "next", MULTIPLE: "multiple", RASTER: "raster", STAGE: "stage", SCREEN: "screen" },
    "flash.automation.StageCaptureEvent": { CAPTURE: "capture" },
    "flash.desktop.ClipboardFormats": { TEXT_FORMAT: "air:text", HTML_FORMAT: "air:html", RICH_TEXT_FORMAT: "air:rtf", URL_FORMAT: "air:url", FILE_LIST_FORMAT: "air:file list", BITMAP_FORMAT: "air:bitmap", FILE_PROMISE_LIST_FORMAT: "air:file promise list" },
    "flash.desktop.ClipboardTransferMode": { ORIGINAL_PREFERRED: "originalPreferred", ORIGINAL_ONLY: "originalOnly", CLONE_PREFERRED: "clonePreferred", CLONE_ONLY: "cloneOnly" },
    "flash.display.ActionScriptVersion": { ACTIONSCRIPT2: 2, ACTIONSCRIPT3: 3 },
    "flash.display.BitmapDataChannel": { RED: 1, GREEN: 2, BLUE: 4, ALPHA: 8 },
    "flash.display.BlendMode": { NORMAL: "normal", LAYER: "layer", MULTIPLY: "multiply", SCREEN: "screen", LIGHTEN: "lighten", DARKEN: "darken", ADD: "add", SUBTRACT: "subtract", DIFFERENCE: "difference", INVERT: "invert", OVERLAY: "overlay", HARDLIGHT: "hardlight", ALPHA: "alpha", ERASE: "erase", SHADER: "shader" },
    "flash.display.CapsStyle": { ROUND: "round", NONE: "none", SQUARE: "square" },
    "flash.display.ColorCorrection": { DEFAULT: "default", ON: "on", OFF: "off" },
    "flash.display.ColorCorrectionSupport": { UNSUPPORTED: "unsupported", DEFAULT_ON: "defaultOn", DEFAULT_OFF: "defaultOff" },
    "flash.display.FocusDirection": { TOP: "top", BOTTOM: "bottom", NONE: "none" },
    "flash.display.GradientType": { LINEAR: "linear", RADIAL: "radial" },
    "flash.display.GraphicsPathCommand": { NO_OP: 0, MOVE_TO: 1, LINE_TO: 2, CURVE_TO: 3, WIDE_MOVE_TO: 4, WIDE_LINE_TO: 5, CUBIC_CURVE_TO: 6 },
    "flash.display.GraphicsPathWinding": { EVEN_ODD: "evenOdd", NON_ZERO: "nonZero" },
    "flash.display.InterpolationMethod": { RGB: "rgb", LINEAR_RGB: "linearRGB" },
    "flash.display.JointStyle": { ROUND: "round", BEVEL: "bevel", MITER: "miter" },
    "flash.display.LineScaleMode": { NORMAL: "normal", VERTICAL: "vertical", HORIZONTAL: "horizontal", NONE: "none" },
    "flash.display.PixelSnapping": { NEVER: "never", ALWAYS: "always", AUTO: "auto" },
    "flash.display.SWFVersion": { FLASH1: 1, FLASH2: 2, FLASH3: 3, FLASH4: 4, FLASH5: 5, FLASH6: 6, FLASH7: 7, FLASH8: 8, FLASH9: 9, FLASH10: 10, FLASH11: 11, FLASH12: 12 },
    "flash.display.ShaderParameterType": { FLOAT: "float", FLOAT2: "float2", FLOAT3: "float3", FLOAT4: "float4", INT: "int", INT2: "int2", INT3: "int3", INT4: "int4", BOOL: "bool", BOOL2: "bool2", BOOL3: "bool3", BOOL4: "bool4", MATRIX2X2: "matrix2x2", MATRIX3X3: "matrix3x3", MATRIX4X4: "matrix4x4" },
    "flash.display.ShaderPrecision": { FULL: "full", FAST: "fast" },
    "flash.display.SpreadMethod": { PAD: "pad", REFLECT: "reflect", REPEAT: "repeat" },
    "flash.display.StageAlign": { TOP: "T", LEFT: "L", BOTTOM: "B", RIGHT: "R", TOP_LEFT: "TL", TOP_RIGHT: "TR", BOTTOM_LEFT: "BL", BOTTOM_RIGHT: "BR" },
    "flash.display.StageDisplayState": { FULL_SCREEN: "fullScreen", FULL_SCREEN_INTERACTIVE: "fullScreenInteractive", NORMAL: "normal" },
    "flash.display.StageQuality": { LOW: "low", MEDIUM: "medium", HIGH: "high", BEST: "best" },
    "flash.display.StageScaleMode": { SHOW_ALL: "showAll", EXACT_FIT: "exactFit", NO_BORDER: "noBorder", NO_SCALE: "noScale" },
    "flash.display.TriangleCulling": { NONE: "none", POSITIVE: "positive", NEGATIVE: "negative" },
    "flash.display3D.Context3DBlendFactor": { ONE: "one", ZERO: "zero", SOURCE_ALPHA: "sourceAlpha", SOURCE_COLOR: "sourceColor", ONE_MINUS_SOURCE_ALPHA: "oneMinusSourceAlpha", ONE_MINUS_SOURCE_COLOR: "oneMinusSourceColor", DESTINATION_ALPHA: "destinationAlpha", DESTINATION_COLOR: "destinationColor", ONE_MINUS_DESTINATION_ALPHA: "oneMinusDestinationAlpha", ONE_MINUS_DESTINATION_COLOR: "oneMinusDestinationColor" },
    "flash.display3D.Context3DCompareMode": { ALWAYS: "always", NEVER: "never", LESS: "less", LESS_EQUAL: "lessEqual", EQUAL: "equal", GREATER_EQUAL: "greaterEqual", GREATER: "greater", NOT_EQUAL: "notEqual" },
    "flash.display3D.Context3DProgramType": { VERTEX: "vertex", FRAGMENT: "fragment" },
    "flash.display3D.Context3DRenderMode": { AUTO: "auto", SOFTWARE: "software" },
    "flash.display3D.Context3DStencilAction": { KEEP: "keep", ZERO: "zero", INCREMENT_SATURATE: "incrementSaturate", DECREMENT_SATURATE: "decrementSaturate", INVERT: "invert", INCREMENT_WRAP: "incrementWrap", DECREMENT_WRAP: "decrementWrap", SET: "set" },
    "flash.display3D.Context3DTextureFormat": { BGRA: "bgra", COMPRESSED: "compressed" },
    "flash.display3D.Context3DTriangleFace": { NONE: "none", BACK: "back", FRONT: "front", FRONT_AND_BACK: "frontAndBack" },
    "flash.display3D.Context3DVertexBufferFormat": { FLOAT_1: "float1", FLOAT_2: "float2", FLOAT_3: "float3", FLOAT_4: "float4", BYTES_4: "bytes4" },
    "flash.events.AccelerometerEvent": { UPDATE: "update" },
    "flash.events.ActivityEvent": { ACTIVITY: "activity" },
    "flash.events.AsyncErrorEvent": { ASYNC_ERROR: "asyncError" },
    "flash.events.ContextMenuEvent": { MENU_ITEM_SELECT: "menuItemSelect", MENU_SELECT: "menuSelect" },
    "flash.events.DRMAuthenticateEvent": { DRM_AUTHENTICATE: "drmAuthenticate", AUTHENTICATION_TYPE_DRM: "drm", AUTHENTICATION_TYPE_PROXY: "proxy" },
    "flash.events.DRMAuthenticationCompleteEvent": { AUTHENTICATION_COMPLETE: "authenticationComplete" },
    "flash.events.DRMAuthenticationErrorEvent": { AUTHENTICATION_ERROR: "authenticationError" },
    "flash.events.DRMDeviceGroupErrorEvent": { ADD_TO_DEVICE_GROUP_ERROR: "addToDeviceGroupError", REMOVE_FROM_DEVICE_GROUP_ERROR: "removeFromDeviceGroupError" },
    "flash.events.DRMDeviceGroupEvent": { ADD_TO_DEVICE_GROUP_COMPLETE: "addToDeviceGroupComplete", REMOVE_FROM_DEVICE_GROUP_COMPLETE: "removeFromDeviceGroupComplete" },
    "flash.events.DRMErrorEvent": { DRM_ERROR: "drmError", DRM_LOAD_DEVICEID_ERROR: "drmLoadDeviceIdError" },
    "flash.events.DRMStatusEvent": { DRM_STATUS: "drmStatus" },
    "flash.events.DataEvent": { DATA: "data", UPLOAD_COMPLETE_DATA: "uploadCompleteData" },
    "flash.events.ErrorEvent": { ERROR: "error" },
    "flash.events.Event": { ACTIVATE: "activate", ADDED: "added", ADDED_TO_STAGE: "addedToStage", CANCEL: "cancel", CHANGE: "change", CLEAR: "clear", CLOSE: "close", COMPLETE: "complete", CONNECT: "connect", COPY: "copy", CUT: "cut", DEACTIVATE: "deactivate", ENTER_FRAME: "enterFrame", FRAME_CONSTRUCTED: "frameConstructed", EXIT_FRAME: "exitFrame", ID3: "id3", INIT: "init", MOUSE_LEAVE: "mouseLeave", OPEN: "open", PASTE: "paste", REMOVED: "removed", REMOVED_FROM_STAGE: "removedFromStage", RENDER: "render", RESIZE: "resize", SCROLL: "scroll", TEXT_INTERACTION_MODE_CHANGE: "textInteractionModeChange", SELECT: "select", SELECT_ALL: "selectAll", SOUND_COMPLETE: "soundComplete", TAB_CHILDREN_CHANGE: "tabChildrenChange", TAB_ENABLED_CHANGE: "tabEnabledChange", TAB_INDEX_CHANGE: "tabIndexChange", UNLOAD: "unload", FULLSCREEN: "fullScreen", CONTEXT3D_CREATE: "context3DCreate" },
    "flash.events.EventPhase": { CAPTURING_PHASE: 1, AT_TARGET: 2, BUBBLING_PHASE: 3 },
    "flash.events.FocusEvent": { FOCUS_IN: "focusIn", FOCUS_OUT: "focusOut", KEY_FOCUS_CHANGE: "keyFocusChange", MOUSE_FOCUS_CHANGE: "mouseFocusChange" },
    "flash.events.FullScreenEvent": { FULL_SCREEN: "fullScreen" },
    "flash.events.GameInputEvent": { DEVICE_ADDED: "deviceAdded", DEVICE_REMOVED: "deviceRemoved" },
    "flash.events.GeolocationEvent": { UPDATE: "update" },
    "flash.events.GestureEvent": { GESTURE_TWO_FINGER_TAP: "gestureTwoFingerTap" },
    "flash.events.GesturePhase": { BEGIN: "begin", UPDATE: "update", END: "end", ALL: "all" },
    "flash.events.HTTPStatusEvent": { HTTP_STATUS: "httpStatus", HTTP_RESPONSE_STATUS: "httpResponseStatus" },
    "flash.events.IMEEvent": { IME_COMPOSITION: "imeComposition", IME_START_COMPOSITION: "imeStartComposition" },
    "flash.events.IOErrorEvent": { IO_ERROR: "ioError", NETWORK_ERROR: "networkError", DISK_ERROR: "diskError", VERIFY_ERROR: "verifyError" },
    "flash.events.KeyboardEvent": { KEY_DOWN: "keyDown", KEY_UP: "keyUp" },
    "flash.events.MouseEvent": { CLICK: "click", DOUBLE_CLICK: "doubleClick", MOUSE_DOWN: "mouseDown", MOUSE_MOVE: "mouseMove", MOUSE_OUT: "mouseOut", MOUSE_OVER: "mouseOver", MOUSE_UP: "mouseUp", MOUSE_WHEEL: "mouseWheel", ROLL_OUT: "rollOut", ROLL_OVER: "rollOver" },
    "flash.events.NetDataEvent": { MEDIA_TYPE_DATA: "mediaTypeData" },
    "flash.events.NetMonitorEvent": { NET_STREAM_CREATE: "netStreamCreate" },
    "flash.events.NetStatusEvent": { NET_STATUS: "netStatus" },
    "flash.events.OutputProgressEvent": { OUTPUT_PROGRESS: "outputProgress" },
    "flash.events.PressAndTapGestureEvent": { GESTURE_PRESS_AND_TAP: "gesturePressAndTap" },
    "flash.events.ProgressEvent": { PROGRESS: "progress", SOCKET_DATA: "socketData" },
    "flash.events.SampleDataEvent": { SAMPLE_DATA: "sampleData" },
    "flash.events.SecurityErrorEvent": { SECURITY_ERROR: "securityError" },
    "flash.events.ShaderEvent": { COMPLETE: "complete" },
    "flash.events.SoftKeyboardEvent": { SOFT_KEYBOARD_ACTIVATE: "softKeyboardActivate", SOFT_KEYBOARD_DEACTIVATE: "softKeyboardDeactivate", SOFT_KEYBOARD_ACTIVATING: "softKeyboardActivating" },
    "flash.events.SoftKeyboardTrigger": { CONTENT_TRIGGERED: "contentTriggered", USER_TRIGGERED: "userTriggered" },
    "flash.events.StageVideoAvailabilityEvent": { STAGE_VIDEO_AVAILABILITY: "stageVideoAvailability" },
    "flash.events.StageVideoEvent": { RENDER_STATE: "renderState", RENDER_STATUS_UNAVAILABLE: "unavailable", RENDER_STATUS_SOFTWARE: "software", RENDER_STATUS_ACCELERATED: "accelerated" },
    "flash.events.StatusEvent": { STATUS: "status" },
    "flash.events.SyncEvent": { SYNC: "sync" },
    "flash.events.TextEvent": { LINK: "link", TEXT_INPUT: "textInput" },
    "flash.events.TimerEvent": { TIMER: "timer", TIMER_COMPLETE: "timerComplete" },
    "flash.events.TouchEvent": { TOUCH_BEGIN: "touchBegin", TOUCH_END: "touchEnd", TOUCH_MOVE: "touchMove", TOUCH_OVER: "touchOver", TOUCH_OUT: "touchOut", TOUCH_ROLL_OVER: "touchRollOver", TOUCH_ROLL_OUT: "touchRollOut", TOUCH_TAP: "touchTap", PROXIMITY_BEGIN: "proximityBegin", PROXIMITY_END: "proximityEnd", PROXIMITY_MOVE: "proximityMove", PROXIMITY_OUT: "proximityOut", PROXIMITY_OVER: "proximityOver", PROXIMITY_ROLL_OUT: "proximityRollOut", PROXIMITY_ROLL_OVER: "proximityRollOver" },
    "flash.events.TransformGestureEvent": { GESTURE_ZOOM: "gestureZoom", GESTURE_PAN: "gesturePan", GESTURE_ROTATE: "gestureRotate", GESTURE_SWIPE: "gestureSwipe" },
    "flash.events.UncaughtErrorEvent": { UNCAUGHT_ERROR: "uncaughtError" },
    "flash.events.VideoEvent": { RENDER_STATE: "renderState", RENDER_STATUS_UNAVAILABLE: "unavailable", RENDER_STATUS_SOFTWARE: "software", RENDER_STATUS_ACCELERATED: "accelerated" },
    "flash.filters.BitmapFilterQuality": { LOW: 1, MEDIUM: 2, HIGH: 3 },
    "flash.filters.BitmapFilterType": { INNER: "inner", OUTER: "outer", FULL: "full" },
    "flash.filters.DisplacementMapFilterMode": { WRAP: "wrap", CLAMP: "clamp", IGNORE: "ignore", COLOR: "color" },
    "flash.geom.Orientation3D": { EULER_ANGLES: "eulerAngles", AXIS_ANGLE: "axisAngle", QUATERNION: "quaternion" },
    "flash.globalization.CollatorMode": { SORTING: "sorting", MATCHING: "matching" },
    "flash.globalization.DateTimeNameContext": { FORMAT: "format", STANDALONE: "standalone" },
    "flash.globalization.DateTimeNameStyle": { FULL: "full", LONG_ABBREVIATION: "longAbbreviation", SHORT_ABBREVIATION: "shortAbbreviation" },
    "flash.globalization.DateTimeStyle": { CUSTOM: "custom", LONG: "long", MEDIUM: "medium", SHORT: "short", NONE: "none" },
    "flash.globalization.LastOperationStatus": { NO_ERROR: "noError", USING_FALLBACK_WARNING: "usingFallbackWarning", USING_DEFAULT_WARNING: "usingDefaultWarning", PARSE_ERROR: "parseError", UNSUPPORTED_ERROR: "unsupportedError", ERROR_CODE_UNKNOWN: "errorCodeUnknown", PATTERN_SYNTAX_ERROR: "patternSyntaxError", MEMORY_ALLOCATION_ERROR: "memoryAllocationError", ILLEGAL_ARGUMENT_ERROR: "illegalArgumentError", BUFFER_OVERFLOW_ERROR: "bufferOverflowError", INVALID_ATTR_VALUE: "invalidAttrValue", NUMBER_OVERFLOW_ERROR: "numberOverflowError", INVALID_CHAR_FOUND: "invalidCharFound", TRUNCATED_CHAR_FOUND: "truncatedCharFound", INDEX_OUT_OF_BOUNDS_ERROR: "indexOutOfBoundsError", PLATFORM_API_FAILED: "platformAPIFailed", UNEXPECTED_TOKEN: "unexpectedToken" },
    "flash.globalization.LocaleID": { DEFAULT: "i-default" },
    "flash.globalization.NationalDigitsType": { EUROPEAN: 48, ARABIC_INDIC: 1632, EXTENDED_ARABIC_INDIC: 1776, NKO: 1984, DEVANAGARI: 2406, BENGALI: 2534, GURMUKHI: 2662, GUJARATI: 2790, ORIYA: 2918, TAMIL: 3046, TELUGU: 3174, KANNADA: 3302, MALAYALAM: 3430, THAI: 3664, LAO: 3792, TIBETAN: 3872, MYANMAR: 4160, MYANMAR_SHAN: 4240, KHMER: 6112, MONGOLIAN: 6160, LIMBU: 6470, NEW_TAI_LUE: 6608, BALINESE: 6992, SUNDANESE: 7088, LEPCHA: 7232, OL_CHIKI: 7248, VAI: 42528, SAURASHTRA: 43216, KAYAH_LI: 43264, CHAM: 43600, FULL_WIDTH: 65296, OSMANYA: 66720 },
    "flash.media.AudioDecoder": { DOLBY_DIGITAL: "DolbyDigital", DOLBY_DIGITAL_PLUS: "DolbyDigitalPlus", DTS: "DTS", DTS_EXPRESS: "DTSExpress", DTS_HD_HIGH_RESOLUTION_AUDIO: "DTSHDHighResolutionAudio", DTS_HD_MASTER_AUDIO: "DTSHDMasterAudio" },
    "flash.media.H264Level": { LEVEL_1: "1", LEVEL_1B: "1b", LEVEL_1_1: "1.1", LEVEL_1_2: "1.2", LEVEL_1_3: "1.3", LEVEL_2: "2", LEVEL_2_1: "2.1", LEVEL_2_2: "2.2", LEVEL_3: "3", LEVEL_3_1: "3.1", LEVEL_3_2: "3.2", LEVEL_4: "4", LEVEL_4_1: "4.1", LEVEL_4_2: "4.2", LEVEL_5: "5", LEVEL_5_1: "5.1" },
    "flash.media.H264Profile": { BASELINE: "baseline", MAIN: "main" },
    "flash.media.MicrophoneEnhancedMode": { FULL_DUPLEX: "fullDuplex", HALF_DUPLEX: "halfDuplex", HEADSET: "headset", SPEAKER_MUTE: "speakerMute", OFF: "off" },
    "flash.media.SoundCodec": { NELLYMOSER: "NellyMoser", SPEEX: "Speex", PCMA: "pcma", PCMU: "pcmu" },
    "flash.media.StageVideoAvailability": { AVAILABLE: "available", UNAVAILABLE: "unavailable" },
    "flash.media.VideoCodec": { H264AVC: "H264Avc", SORENSON: "Sorenson" },
    "flash.media.VideoStatus": { UNAVAILABLE: "unavailable", SOFTWARE: "software", ACCELERATED: "accelerated" },
    "flash.net.NetGroupReceiveMode": { EXACT: "exact", NEAREST: "nearest" },
    "flash.net.NetGroupReplicationStrategy": { RAREST_FIRST: "rarestFirst", LOWEST_FIRST: "lowestFirst" },
    "flash.net.NetGroupSendMode": { NEXT_INCREASING: "nextIncreasing", NEXT_DECREASING: "nextDecreasing" },
    "flash.net.NetGroupSendResult": { ERROR: "error", NO_ROUTE: "no route", SENT: "sent" },
    "flash.net.NetStream": { DIRECT_CONNECTIONS: "directConnections", CONNECT_TO_FMS: "connectToFMS" },
    "flash.net.NetStreamAppendBytesAction": { RESET_BEGIN: "resetBegin", RESET_SEEK: "resetSeek", END_SEQUENCE: "endSequence" },
    "flash.net.NetStreamPlayTransitions": { APPEND: "append", RESET: "reset", SWITCH: "switch", SWAP: "swap", STOP: "stop", RESUME: "resume", APPEND_AND_WAIT: "appendAndWait" },
    "flash.net.ObjectEncoding": { AMF0: 0, AMF3: 3, DEFAULT: 3 },
    "flash.net.SharedObjectFlushStatus": { FLUSHED: "flushed", PENDING: "pending" },
    "flash.net.URLLoaderDataFormat": { TEXT: "text", BINARY: "binary", VARIABLES: "variables" },
    "flash.net.URLRequestMethod": { POST: "POST", GET: "GET", PUT: "PUT", DELETE: "DELETE", HEAD: "HEAD", OPTIONS: "OPTIONS" },
    "flash.net.drm.AddToDeviceGroupSetting": { FORCE_REFRESH: "forceRefresh", LOCAL_ONLY: "localOnly", ALLOW_SERVER: "allowServer" },
    "flash.net.drm.AuthenticationMethod": { ANONYMOUS: "anonymous", USERNAME_AND_PASSWORD: "usernameAndPassword" },
    "flash.net.drm.LoadVoucherSetting": { FORCE_REFRESH: "forceRefresh", LOCAL_ONLY: "localOnly", ALLOW_SERVER: "allowServer" },
    "flash.printing.PrintJobOrientation": { LANDSCAPE: "landscape", PORTRAIT: "portrait" },
    "flash.security.CertificateStatus": { TRUSTED: "trusted", UNKNOWN: "unknown", INVALID: "invalid", EXPIRED: "expired", NOT_YET_VALID: "notYetValid", PRINCIPAL_MISMATCH: "principalMismatch", UNTRUSTED_SIGNERS: "untrustedSigners", REVOKED: "revoked", INVALID_CHAIN: "invalidChain" },
    "flash.system.IMEConversionMode": { ALPHANUMERIC_FULL: "ALPHANUMERIC_FULL", ALPHANUMERIC_HALF: "ALPHANUMERIC_HALF", CHINESE: "CHINESE", JAPANESE_HIRAGANA: "JAPANESE_HIRAGANA", JAPANESE_KATAKANA_FULL: "JAPANESE_KATAKANA_FULL", JAPANESE_KATAKANA_HALF: "JAPANESE_KATAKANA_HALF", KOREAN: "KOREAN", UNKNOWN: "UNKNOWN" },
    "flash.system.ImageDecodingPolicy": { ON_DEMAND: "onDemand", ON_LOAD: "onLoad" },
    "flash.system.Security": { REMOTE: "remote", LOCAL_WITH_FILE: "localWithFile", LOCAL_WITH_NETWORK: "localWithNetwork", LOCAL_TRUSTED: "localTrusted", APPLICATION: "application" },
    "flash.system.SecurityPanel": { DEFAULT: "default", PRIVACY: "privacy", LOCAL_STORAGE: "localStorage", MICROPHONE: "microphone", CAMERA: "camera", DISPLAY: "display", SETTINGS_MANAGER: "settingsManager" },
    "flash.system.SystemUpdaterType": { SYSTEM: "system", DRM: "drm" },
    "flash.system.TouchscreenType": { FINGER: "finger", STYLUS: "stylus", NONE: "none" },
    "flash.text.AntiAliasType": { NORMAL: "normal", ADVANCED: "advanced" },
    "flash.text.FontStyle": { REGULAR: "regular", BOLD: "bold", ITALIC: "italic", BOLD_ITALIC: "boldItalic" },
    "flash.text.FontType": { EMBEDDED: "embedded", EMBEDDED_CFF: "embeddedCFF", DEVICE: "device" },
    "flash.text.GridFitType": { NONE: "none", PIXEL: "pixel", SUBPIXEL: "subpixel" },
    "flash.text.TextColorType": { DARK_COLOR: "dark", LIGHT_COLOR: "light" },
    "flash.text.TextDisplayMode": { LCD: "lcd", CRT: "crt", DEFAULT: "default" },
    "flash.text.TextFieldAutoSize": { NONE: "none", LEFT: "left", CENTER: "center", RIGHT: "right" },
    "flash.text.TextFieldType": { INPUT: "input", DYNAMIC: "dynamic" },
    "flash.text.TextFormatAlign": { LEFT: "left", CENTER: "center", RIGHT: "right", JUSTIFY: "justify", START: "start", END: "end" },
    "flash.text.TextFormatDisplay": { INLINE: "inline", BLOCK: "block" },
    "flash.text.TextInteractionMode": { NORMAL: "normal", SELECTION: "selection" },
    "flash.text.engine.BreakOpportunity": { AUTO: "auto", ANY: "any", NONE: "none", ALL: "all" },
    "flash.text.engine.CFFHinting": { NONE: "none", HORIZONTAL_STEM: "horizontalStem" },
    "flash.text.engine.ContentElement": { GRAPHIC_ELEMENT: 65007 },
    "flash.text.engine.DigitCase": { DEFAULT: "default", LINING: "lining", OLD_STYLE: "oldStyle" },
    "flash.text.engine.DigitWidth": { DEFAULT: "default", PROPORTIONAL: "proportional", TABULAR: "tabular" },
    "flash.text.engine.FontLookup": { DEVICE: "device", EMBEDDED_CFF: "embeddedCFF" },
    "flash.text.engine.FontPosture": { NORMAL: "normal", ITALIC: "italic" },
    "flash.text.engine.FontWeight": { NORMAL: "normal", BOLD: "bold" },
    "flash.text.engine.JustificationStyle": { PUSH_IN_KINSOKU: "pushInKinsoku", PUSH_OUT_ONLY: "pushOutOnly", PRIORITIZE_LEAST_ADJUSTMENT: "prioritizeLeastAdjustment" },
    "flash.text.engine.Kerning": { ON: "on", OFF: "off", AUTO: "auto" },
    "flash.text.engine.LigatureLevel": { NONE: "none", MINIMUM: "minimum", COMMON: "common", UNCOMMON: "uncommon", EXOTIC: "exotic" },
    "flash.text.engine.LineJustification": { UNJUSTIFIED: "unjustified", ALL_BUT_LAST: "allButLast", ALL_INCLUDING_LAST: "allIncludingLast", ALL_BUT_MANDATORY_BREAK: "allButMandatoryBreak" },
    "flash.text.engine.RenderingMode": { NORMAL: "normal", CFF: "cff" },
    "flash.text.engine.TabAlignment": { START: "start", CENTER: "center", END: "end", DECIMAL: "decimal" },
    "flash.text.engine.TextBaseline": { ROMAN: "roman", ASCENT: "ascent", DESCENT: "descent", IDEOGRAPHIC_TOP: "ideographicTop", IDEOGRAPHIC_CENTER: "ideographicCenter", IDEOGRAPHIC_BOTTOM: "ideographicBottom", USE_DOMINANT_BASELINE: "useDominantBaseline" },
    "flash.text.engine.TextLine": { MAX_LINE_WIDTH: 1000000 },
    "flash.text.engine.TextLineCreationResult": { SUCCESS: "success", EMERGENCY: "emergency", COMPLETE: "complete", INSUFFICIENT_WIDTH: "insufficientWidth" },
    "flash.text.engine.TextLineValidity": { VALID: "valid", POSSIBLY_INVALID: "possiblyInvalid", INVALID: "invalid", STATIC: "static" },
    "flash.text.engine.TextRotation": { ROTATE_0: "rotate0", ROTATE_90: "rotate90", ROTATE_180: "rotate180", ROTATE_270: "rotate270", AUTO: "auto" },
    "flash.text.engine.TypographicCase": { DEFAULT: "default", TITLE: "title", CAPS: "caps", SMALL_CAPS: "smallCaps", UPPERCASE: "uppercase", LOWERCASE: "lowercase", CAPS_AND_SMALL_CAPS: "capsAndSmallCaps" },
    "flash.trace.Trace": { OFF: 0, METHODS: 1, METHODS_WITH_ARGS: 2, METHODS_AND_LINES: 3, METHODS_AND_LINES_WITH_ARGS: 4, FILE: 1, LISTENER: 2 },
    "flash.ui.GameInputControlType": { MOVEMENT: "movement", ROTATION: "rotation", DIRECTION: "direction", ACCELERATION: "acceleration", BUTTON: "button", TRIGGER: "trigger" },
    "flash.ui.GameInputDevice": { MAX_BUFFER_SIZE: 4800 },
    "flash.ui.GameInputFinger": { THUMB: "thumb", INDEX: "index", MIDDLE: "middle", UNKNOWN: "unknown" },
    "flash.ui.GameInputHand": { RIGHT: "right", LEFT: "left", UNKNOWN: "unknown" },
    "flash.ui.KeyLocation": { STANDARD: 0, LEFT: 1, RIGHT: 2, NUM_PAD: 3, D_PAD: 4 },
    "flash.ui.Keyboard": { KEYNAME_UPARROW: "Up", KEYNAME_DOWNARROW: "Down", KEYNAME_LEFTARROW: "Left", KEYNAME_RIGHTARROW: "Right", KEYNAME_F1: "F1", KEYNAME_F2: "F2", KEYNAME_F3: "F3", KEYNAME_F4: "F4", KEYNAME_F5: "F5", KEYNAME_F6: "F6", KEYNAME_F7: "F7", KEYNAME_F8: "F8", KEYNAME_F9: "F9", KEYNAME_F10: "F10", KEYNAME_F11: "F11", KEYNAME_F12: "F12", KEYNAME_F13: "F13", KEYNAME_F14: "F14", KEYNAME_F15: "F15", KEYNAME_F16: "F16", KEYNAME_F17: "F17", KEYNAME_F18: "F18", KEYNAME_F19: "F19", KEYNAME_F20: "F20", KEYNAME_F21: "F21", KEYNAME_F22: "F22", KEYNAME_F23: "F23", KEYNAME_F24: "F24", KEYNAME_F25: "F25", KEYNAME_F26: "F26", KEYNAME_F27: "F27", KEYNAME_F28: "F28", KEYNAME_F29: "F29", KEYNAME_F30: "F30", KEYNAME_F31: "F31", KEYNAME_F32: "F32", KEYNAME_F33: "F33", KEYNAME_F34: "F34", KEYNAME_F35: "F35", KEYNAME_INSERT: "Insert", KEYNAME_DELETE: "Delete", KEYNAME_HOME: "Home", KEYNAME_BEGIN: "Begin", KEYNAME_END: "End", KEYNAME_PAGEUP: "PgUp", KEYNAME_PAGEDOWN: "PgDn", KEYNAME_PRINTSCREEN: "PrntScrn", KEYNAME_SCROLLLOCK: "ScrlLck", KEYNAME_PAUSE: "Pause", KEYNAME_SYSREQ: "SysReq", KEYNAME_BREAK: "Break", KEYNAME_RESET: "Reset", KEYNAME_STOP: "Stop", KEYNAME_MENU: "Menu", KEYNAME_USER: "User", KEYNAME_SYSTEM: "Sys", KEYNAME_PRINT: "Print", KEYNAME_CLEARLINE: "ClrLn", KEYNAME_CLEARDISPLAY: "ClrDsp", KEYNAME_INSERTLINE: "InsLn", KEYNAME_DELETELINE: "DelLn", KEYNAME_INSERTCHAR: "InsChr", KEYNAME_DELETECHAR: "DelChr", KEYNAME_PREV: "Prev", KEYNAME_NEXT: "Next", KEYNAME_SELECT: "Select", KEYNAME_EXECUTE: "Exec", KEYNAME_UNDO: "Undo", KEYNAME_REDO: "Redo", KEYNAME_FIND: "Find", KEYNAME_HELP: "Help", KEYNAME_MODESWITCH: "ModeSw", STRING_UPARROW: "", STRING_DOWNARROW: "", STRING_LEFTARROW: "", STRING_RIGHTARROW: "", STRING_F1: "", STRING_F2: "", STRING_F3: "", STRING_F4: "", STRING_F5: "", STRING_F6: "", STRING_F7: "", STRING_F8: "", STRING_F9: "", STRING_F10: "", STRING_F11: "", STRING_F12: "", STRING_F13: "", STRING_F14: "", STRING_F15: "", STRING_F16: "", STRING_F17: "", STRING_F18: "", STRING_F19: "", STRING_F20: "", STRING_F21: "", STRING_F22: "", STRING_F23: "", STRING_F24: "", STRING_F25: "", STRING_F26: "", STRING_F27: "", STRING_F28: "", STRING_F29: "", STRING_F30: "", STRING_F31: "", STRING_F32: "", STRING_F33: "", STRING_F34: "", STRING_F35: "", STRING_INSERT: "", STRING_DELETE: "", STRING_HOME: "", STRING_BEGIN: "", STRING_END: "", STRING_PAGEUP: "", STRING_PAGEDOWN: "", STRING_PRINTSCREEN: "", STRING_SCROLLLOCK: "", STRING_PAUSE: "", STRING_SYSREQ: "", STRING_BREAK: "", STRING_RESET: "", STRING_STOP: "", STRING_MENU: "", STRING_USER: "", STRING_SYSTEM: "", STRING_PRINT: "", STRING_CLEARLINE: "", STRING_CLEARDISPLAY: "", STRING_INSERTLINE: "", STRING_DELETELINE: "", STRING_INSERTCHAR: "", STRING_DELETECHAR: "", STRING_PREV: "", STRING_NEXT: "", STRING_SELECT: "", STRING_EXECUTE: "", STRING_UNDO: "", STRING_REDO: "", STRING_FIND: "", STRING_HELP: "", STRING_MODESWITCH: "", NUMBER_0: 48, NUMBER_1: 49, NUMBER_2: 50, NUMBER_3: 51, NUMBER_4: 52, NUMBER_5: 53, NUMBER_6: 54, NUMBER_7: 55, NUMBER_8: 56, NUMBER_9: 57, A: 65, B: 66, C: 67, D: 68, E: 69, F: 70, G: 71, H: 72, I: 73, J: 74, K: 75, L: 76, M: 77, N: 78, O: 79, P: 80, Q: 81, R: 82, S: 83, T: 84, U: 85, V: 86, W: 87, X: 88, Y: 89, Z: 90, SEMICOLON: 186, EQUAL: 187, COMMA: 188, MINUS: 189, PERIOD: 190, SLASH: 191, BACKQUOTE: 192, LEFTBRACKET: 219, BACKSLASH: 220, RIGHTBRACKET: 221, QUOTE: 222, ALTERNATE: 18, BACKSPACE: 8, CAPS_LOCK: 20, COMMAND: 15, CONTROL: 17, DELETE: 46, DOWN: 40, END: 35, ENTER: 13, ESCAPE: 27, F1: 112, F2: 113, F3: 114, F4: 115, F5: 116, F6: 117, F7: 118, F8: 119, F9: 120, F10: 121, F11: 122, F12: 123, F13: 124, F14: 125, F15: 126, HOME: 36, INSERT: 45, LEFT: 37, NUMPAD: 21, NUMPAD_0: 96, NUMPAD_1: 97, NUMPAD_2: 98, NUMPAD_3: 99, NUMPAD_4: 100, NUMPAD_5: 101, NUMPAD_6: 102, NUMPAD_7: 103, NUMPAD_8: 104, NUMPAD_9: 105, NUMPAD_ADD: 107, NUMPAD_DECIMAL: 110, NUMPAD_DIVIDE: 111, NUMPAD_ENTER: 108, NUMPAD_MULTIPLY: 106, NUMPAD_SUBTRACT: 109, PAGE_DOWN: 34, PAGE_UP: 33, RIGHT: 39, SHIFT: 16, SPACE: 32, TAB: 9, UP: 38, RED: 16777216, GREEN: 16777217, YELLOW: 16777218, BLUE: 16777219, CHANNEL_UP: 16777220, CHANNEL_DOWN: 16777221, RECORD: 16777222, PLAY: 16777223, PAUSE: 16777224, STOP: 16777225, FAST_FORWARD: 16777226, REWIND: 16777227, SKIP_FORWARD: 16777228, SKIP_BACKWARD: 16777229, NEXT: 16777230, PREVIOUS: 16777231, LIVE: 16777232, LAST: 16777233, MENU: 16777234, INFO: 16777235, GUIDE: 16777236, EXIT: 16777237, BACK: 16777238, AUDIO: 16777239, SUBTITLE: 16777240, DVR: 16777241, VOD: 16777242, INPUT: 16777243, SETUP: 16777244, HELP: 16777245, MASTER_SHELL: 16777246, SEARCH: 16777247 },
    "flash.ui.KeyboardType": { ALPHANUMERIC: "alphanumeric", KEYPAD: "keypad", NONE: "none" },
    "flash.ui.MouseCursor": { AUTO: "auto", ARROW: "arrow", BUTTON: "button", HAND: "hand", IBEAM: "ibeam" },
    "flash.ui.MultitouchInputMode": { NONE: "none", GESTURE: "gesture", TOUCH_POINT: "touchPoint" },
    "flash.utils.CompressionAlgorithm": { ZLIB: "zlib", DEFLATE: "deflate" },
    "flash.utils.Endian": { BIG_ENDIAN: "bigEndian", LITTLE_ENDIAN: "littleEndian" },
    "flash.xml.XMLNodeType": { ELEMENT_NODE: 1, TEXT_NODE: 3, CDATA_NODE: 4, PROCESSING_INSTRUCTION_NODE: 7, COMMENT_NODE: 8, DOCUMENT_TYPE_NODE: 10, XML_DECLARATION: 13 },
};
